import VibeSite.Site

namespace VibeSite.Example

private def home : VibeSite.Page := {
  route := "/"
  title := "A site, proven small"
  description := "A dependency-free static site generated by Lean 4."
  markdown := """
This is **VibeSite**: a deliberately compact static site generator written in Lean 4.

It treats the site as typed data, rejects duplicate or unsafe routes, escapes generated HTML, and emits plain files that can be hosted almost anywhere.

> The compiler is part of the publishing pipeline.

## What it understands

- headings and paragraphs
- **strong text**, *emphasis*, `inline code`, and [links](https://lean-lang.org/)
- ordered and unordered lists
- quotes, rules, and fenced code blocks

```lean
#eval VibeSite.Route.href "/notes/hello"
-- /notes/hello/
```

---

Read the [design note](/design/) or inspect the source.
"""
}

private def design : VibeSite.Page := {
  route := "/design/"
  title := "Design"
  description := "Why this generator is intentionally small."
  markdown := """
## Constraints are the architecture

VibeSite has no runtime framework and no JavaScript requirement. The first release uses only Lean's standard library.

1. Pages are records.
2. Routes are normalized and validated.
3. Markdown becomes a small HTML tree.
4. Text and attributes are escaped at render time.
5. The result is a directory of static files.

## Why Lean?

Not because HTML needs theorem proving. Because publishing pipelines benefit from **explicit invariants**, total data models, and executable configuration.

The useful next step is to refine route validity from a runtime check into a constructor that only admits safe routes.
"""
}

private def colophon : VibeSite.Page := {
  route := "/colophon"
  title := "Colophon"
  markdown := """
Built with Lean 4 and Lake. No third-party packages.

The visual system uses system fonts, a restrained reading width, automatic dark mode, and one generated stylesheet.
"""
}

def site : VibeSite.SiteConfig := {
  title := "VibeSite"
  tagline := "A tiny static site generator in Lean 4."
  baseUrl := "https://example.com"
  pages := [home, design, colophon]
  navigation := [
    { label := "Home", route := "/" },
    { label := "Design", route := "/design/" },
    { label := "Colophon", route := "/colophon/" }
  ]
}

end VibeSite.Example
