import LeanSite.Site

namespace LeanSite.Example

private def markdownText (lines : List String) : String :=
  String.intercalate "\n" lines ++ "\n"

private def home : LeanSite.Page := {
  route := "/"
  title := "A site, proven small"
  description := "A dependency-free static site generated by Lean 4."
  markdown := markdownText [
    "This is **LeanSite**: a deliberately compact static site generator written in Lean 4.",
    "",
    "It treats the site as typed data, rejects duplicate or unsafe routes, escapes generated HTML, and emits plain files that can be hosted almost anywhere.",
    "",
    "> The compiler is part of the publishing pipeline.",
    "",
    "## What it understands",
    "",
    "- headings and paragraphs",
    "- **strong text**, *emphasis*, `inline code`, and [links](https://lean-lang.org/)",
    "- ordered and unordered lists",
    "- quotes, rules, and fenced code blocks",
    "- project-path deployment, including GitHub Pages",
    "",
    "```lean",
    "#eval LeanSite.Route.href \"/notes/hello\"",
    "-- /notes/hello/",
    "```",
    "",
    "---",
    "",
    "Read the [design note](/design/) or inspect the source on [GitHub](https://github.com/fyremael/LEANSITE)."
  ]
}

private def design : LeanSite.Page := {
  route := "/design/"
  title := "Design"
  description := "Why this generator is intentionally small."
  markdown := markdownText [
    "## Constraints are the architecture",
    "",
    "LeanSite has no runtime framework and no JavaScript requirement. The first release uses only Lean's standard library.",
    "",
    "1. Pages are records.",
    "2. Routes and deployment paths are normalized and validated.",
    "3. Markdown becomes a small HTML tree.",
    "4. Text and attributes are escaped at render time.",
    "5. The result is a directory of static files.",
    "",
    "## Why Lean?",
    "",
    "Not because HTML needs theorem proving. Because publishing pipelines benefit from **explicit invariants**, total data models, and executable configuration.",
    "",
    "The useful next step is to refine route validity from a runtime check into a constructor that only admits safe routes."
  ]
}

private def colophon : LeanSite.Page := {
  route := "/colophon"
  title := "Colophon"
  markdown := markdownText [
    "Built with Lean 4 and Lake. No third-party Lean packages.",
    "",
    "The visual system uses system fonts, a restrained reading width, automatic dark mode, and one generated stylesheet.",
    "",
    "This public demo is compiled and deployed to GitHub Pages by the repository workflow."
  ]
}

def site : LeanSite.SiteConfig := {
  title := "LeanSite"
  tagline := "A tiny static site generator in Lean 4."
  baseUrl := "https://fyremael.github.io"
  basePath := "/LEANSITE"
  pages := [home, design, colophon]
  navigation := [
    { label := "Home", route := "/" },
    { label := "Design", route := "/design/" },
    { label := "Colophon", route := "/colophon/" }
  ]
}

end LeanSite.Example
