import LeanSite.Site

namespace LeanSite.Example

private def markdownText (lines : List String) : String :=
  String.intercalate "\n" lines ++ "\n"

private def homeRoute : LeanSite.Route :=
  Route.root

private def designRoute : LeanSite.Route :=
  Route.ofSegments ["design"] (by decide)

private def colophonRoute : LeanSite.Route :=
  Route.ofSegments ["colophon"] (by decide)

private def home : LeanSite.Page := {
  route := homeRoute
  title := "A site, proven small"
  description := "A dependency-free static site generated by Lean 4."
  markdown := markdownText [
    "This is **LeanSite**: a deliberately compact static site generator written in Lean 4.",
    "",
    "It treats the site as typed data, makes unsafe page routes unrepresentable, escapes generated HTML, and emits plain files that can be hosted almost anywhere.",
    "",
    "> The compiler is part of the publishing pipeline.",
    "",
    "## What it understands",
    "",
    "- headings and paragraphs",
    "- **strong text**, *emphasis*, `inline code`, and [links](https://lean-lang.org/)",
    "- ordered and unordered lists",
    "- quotes, rules, and fenced code blocks",
    "- project-path deployment, including GitHub Pages",
    "- compiler-certified logical routes",
    "",
    "```lean",
    "#eval LeanSite.Route.href (LeanSite.Route.ofSegments [\"notes\", \"hello\"] (by decide))",
    "-- /notes/hello/",
    "```",
    "",
    "---",
    "",
    "Read the [design note](/design/) or inspect the source on [GitHub](https://github.com/fyremael/LEANSITE)."
  ]
}

private def design : LeanSite.Page := {
  route := designRoute
  title := "Design"
  description := "Why this generator is intentionally small."
  markdown := markdownText [
    "## Constraints are the architecture",
    "",
    "LeanSite has no runtime framework and no JavaScript requirement. The first release uses only Lean's standard library.",
    "",
    "1. Pages are records.",
    "2. Page routes are values with a private constructor and certified safe segments.",
    "3. Deployment paths remain separate and are validated before emission.",
    "4. Markdown becomes a small HTML tree.",
    "5. Text and attributes are escaped at render time.",
    "6. The result is a directory of static files.",
    "",
    "## Why Lean?",
    "",
    "Not because HTML needs theorem proving. Because publishing pipelines benefit from **explicit invariants**, total data models, and executable configuration.",
    "",
    "Unsafe page routes are rejected at construction rather than discovered during the site build."
  ]
}

private def colophon : LeanSite.Page := {
  route := colophonRoute
  title := "Colophon"
  markdown := markdownText [
    "Built with Lean 4 and Lake. No third-party Lean packages.",
    "",
    "The visual system uses system fonts, a restrained reading width, automatic dark mode, and one generated stylesheet.",
    "",
    "This public demo is compiled and deployed to GitHub Pages by the repository workflow."
  ]
}

def site : LeanSite.SiteConfig := {
  title := "LeanSite"
  tagline := "A tiny static site generator in Lean 4."
  baseUrl := "https://fyremael.github.io"
  basePath := "/LEANSITE"
  pages := [home, design, colophon]
  navigation := [
    { label := "Home", route := homeRoute },
    { label := "Design", route := designRoute },
    { label := "Colophon", route := colophonRoute }
  ]
}

end LeanSite.Example
