import LeanSite.Markdown

namespace LeanSite

open Html

structure Page where
  route : Route
  title : String
  markdown : String
  description : String := ""
  draft : Bool := false
  deriving Repr, Inhabited

structure NavItem where
  label : String
  route : Route
  deriving Repr, Inhabited

structure SiteConfig where
  title : String
  tagline : String := ""
  baseUrl : String := ""
  basePath : String := ""
  language : String := "en"
  outputDir : System.FilePath := System.FilePath.mk "_site"
  pages : List Page := []
  navigation : List NavItem := []
  deriving Repr, Inhabited

inductive ValidationError where
  | duplicateRoute : String → ValidationError
  | unsafeBasePath : String → ValidationError
  | missingNavigationTarget : String → ValidationError
  deriving Repr, Inhabited

private def firstDuplicate? [BEq α] (values : List α) : Option α :=
  let rec go (seen : List α) : List α → Option α
    | [] => none
    | value :: rest =>
        if seen.contains value then some value else go (value :: seen) rest
  go [] values

def validate (site : SiteConfig) : List ValidationError :=
  let published := site.pages.filter fun page => !page.draft
  let routes := published.map fun page => page.route
  let basePathErrors :=
    if BasePath.hasUnsafeSegment site.basePath then
      [ValidationError.unsafeBasePath site.basePath]
    else
      []
  let duplicates :=
    match firstDuplicate? routes with
    | some route => [ValidationError.duplicateRoute (Route.href route)]
    | none => []
  let missingNav := site.navigation.filterMap fun item =>
    if routes.contains item.route then
      none
    else
      some (ValidationError.missingNavigationTarget (Route.href item.route))
  basePathErrors ++ duplicates ++ missingNav

private def validationMessage : ValidationError → String
  | .duplicateRoute route => s!"duplicate route: {route}"
  | .unsafeBasePath path => s!"unsafe deployment base path: {path}"
  | .missingNavigationTarget route => s!"navigation target has no published page: {route}"

private def trimTrailingSlash (input : String) : String :=
  let reversed := input.toList.reverse.dropWhile fun c => c == '/'
  String.ofList reversed.reverse

private def publicHref (site : SiteConfig) (route : Route) : String :=
  BasePath.resolve site.basePath (Route.href route)

private def absoluteUrl (site : SiteConfig) (route : Route) : String :=
  s!"{trimTrailingSlash site.baseUrl}{publicHref site route}"

private def renderNavigation (site : SiteConfig) (activeRoute : Route) : Html :=
  let links := site.navigation.map fun item =>
    let attrs :=
      if item.route == activeRoute then
        [("href", publicHref site item.route), ("aria-current", "page")]
      else
        [("href", publicHref site item.route)]
    Html.nodeA "a" attrs [Html.txt item.label]
  Html.nodeA "nav" [("aria-label", "Primary")] links

private def pageDocument (site : SiteConfig) (page : Page) : String :=
  let description := if page.description.isEmpty then site.tagline else page.description
  let canonical := if site.baseUrl.isEmpty then [] else [
    Html.nodeA "link" [("rel", "canonical"), ("href", absoluteUrl site page.route)]
  ]
  let head := Html.node "head" <| [
    Html.nodeA "meta" [("charset", "utf-8")],
    Html.nodeA "meta" [("name", "viewport"), ("content", "width=device-width, initial-scale=1")],
    Html.node "title" [Html.txt s!"{page.title} · {site.title}"],
    Html.nodeA "meta" [("name", "description"), ("content", description)],
    Html.nodeA "link" [("rel", "stylesheet"), ("href", BasePath.resolve site.basePath "/style.css")]
  ] ++ canonical
  let header := Html.node "header" [
    Html.nodeA "a" [("class", "site-title"), ("href", publicHref site Route.root)] [Html.txt site.title],
    renderNavigation site page.route
  ]
  let article := Html.node "article" [
    Html.nodeA "header" [("class", "page-header")] [Html.node "h1" [Html.txt page.title]],
    Markdown.renderWithBasePath site.basePath page.markdown
  ]
  let footer := Html.node "footer" [Html.txt "Generated by LeanSite in Lean 4."]
  let body := Html.node "body" [header, Html.node "main" [article], footer]
  "<!doctype html>\n" ++ Html.render (Html.nodeA "html" [("lang", site.language)] [head, body]) ++ "\n"

private def stylesheet : String :=
  String.intercalate "\n" [
    ":root {",
    "  color-scheme: light dark;",
    "  --bg: #f6f3ec;",
    "  --ink: #171713;",
    "  --muted: #66645d;",
    "  --line: #d8d3c8;",
    "  --accent: #315c4c;",
    "  --code: #ebe6dc;",
    "  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;",
    "}",
    "@media (prefers-color-scheme: dark) {",
    "  :root { --bg:#141512; --ink:#ecebe5; --muted:#aaa89e; --line:#383a34; --accent:#93c9b1; --code:#22241f; }",
    "}",
    "* { box-sizing: border-box; }",
    "body { margin:0; background:var(--bg); color:var(--ink); line-height:1.65; }",
    "body > header, main, body > footer { width:min(74ch, calc(100% - 2rem)); margin-inline:auto; }",
    "body > header { display:flex; align-items:center; justify-content:space-between; gap:1rem; padding:1.2rem 0; border-bottom:1px solid var(--line); }",
    ".site-title { color:var(--ink); font-weight:750; text-decoration:none; letter-spacing:-0.02em; }",
    "nav { display:flex; flex-wrap:wrap; gap:.85rem; }",
    "nav a { color:var(--muted); text-decoration:none; }",
    "nav a[aria-current=\"page\"], nav a:hover { color:var(--accent); }",
    "main { min-height:75vh; padding:4rem 0 6rem; }",
    ".page-header { margin-bottom:2rem; }",
    "h1, h2, h3 { line-height:1.15; letter-spacing:-0.035em; }",
    "h1 { font-size:clamp(2.4rem, 8vw, 5rem); margin:0; }",
    "h2 { margin-top:2.5rem; }",
    "a { color:var(--accent); text-underline-offset:.18em; }",
    "blockquote { margin:2rem 0; padding:.2rem 0 .2rem 1.2rem; border-left:3px solid var(--accent); color:var(--muted); }",
    "pre { overflow:auto; padding:1rem; border:1px solid var(--line); border-radius:.5rem; background:var(--code); }",
    "code { font-family:ui-monospace, SFMono-Regular, Consolas, monospace; font-size:.92em; }",
    ":not(pre) > code { padding:.12rem .3rem; border-radius:.25rem; background:var(--code); }",
    "hr { border:0; border-top:1px solid var(--line); margin:3rem 0; }",
    "body > footer { padding:1.5rem 0 3rem; border-top:1px solid var(--line); color:var(--muted); font-size:.9rem; }"
  ] ++ "\n"

private def sitemap (site : SiteConfig) : String :=
  let urls := (site.pages.filter fun page => !page.draft).map fun page =>
    s!"  <url><loc>{Html.escapeText (absoluteUrl site page.route)}</loc></url>"
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" ++
  "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n" ++
  String.intercalate "\n" urls ++ "\n</urlset>\n"

private def robots (site : SiteConfig) : String :=
  if site.baseUrl.isEmpty then
    "User-agent: *\nAllow: /\n"
  else
    let sitemapPath := BasePath.resolve site.basePath "/sitemap.xml"
    s!"User-agent: *\nAllow: /\nSitemap: {trimTrailingSlash site.baseUrl}{sitemapPath}\n"

private def writePage (site : SiteConfig) (page : Page) : IO Unit := do
  let directory := Route.directory site.outputDir page.route
  IO.FS.createDirAll directory
  IO.FS.writeFile (directory / "index.html") (pageDocument site page)
  IO.println s!"  wrote {publicHref site page.route}"

def build (site : SiteConfig) : IO Unit := do
  let errors := validate site
  unless errors.isEmpty do
    let details := String.intercalate "\n" (errors.map fun error => s!"- {validationMessage error}")
    throw <| IO.userError s!"Site validation failed:\n{details}"
  IO.FS.createDirAll site.outputDir
  IO.FS.writeFile (site.outputDir / ".nojekyll") ""
  IO.FS.writeFile (site.outputDir / "style.css") stylesheet
  IO.FS.writeFile (site.outputDir / "robots.txt") (robots site)
  unless site.baseUrl.isEmpty do
    IO.FS.writeFile (site.outputDir / "sitemap.xml") (sitemap site)
  IO.println s!"Building {site.title} → {site.outputDir}"
  for page in site.pages do
    unless page.draft do
      writePage site page
  IO.println "Done."

end LeanSite
